### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by mwkcoding** [beyondcode/laravel-favicon#16]
Is this in the works?

We have a project where we use PHP 8.0 and would love to use this package to distinguish between production and development tabs in the browser.

**Comment by mwkcoding** [comment]
Maybe #14 would close this?

**Comment by vajda-media** [comment]
Seem like no support anymore on this :(

**Comment by mwkcoding** [comment]
@vajda-media PR was merged long ago and release was made. So it does support PHP8
