### ISSUE TITLE
Make it a dev dependency

### ISSUE THREAD

**Issue by winkbrace** [beyondcode/laravel-favicon#3]
Very nice little quality of life feature.

But I only need this dependency in my development and test environments, so it qualifies as a dev dependency. So the first thing I did was add a custom helper method for the production environment. 

```php
/**
 * Placeholder for the laravel-favicon package that doesn't exist on production
 */
if ( ! function_exists('favicon') && env('APP_ENV') == 'production') {
    function favicon($image)
    {
        return $image;
    }
}
```

I'm sure you already thought about this, but I'd like to propose adding this option to the readme. What do you think?

**Comment by zlodes** [comment]
What about developers who wants use it on production too? :)

**Comment by winkbrace** [comment]
I have the feeling this is not really actively maintained anymore. :)
So I'm closing this issue. It was just a question anyway.
